---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aks.mydomain.xyz # This should be your domain name
  namespace: default
spec:
  secretName: aks.mydomain.xyz-tls # This will be your cert name in Kubernetes
  issuerRef:
    name: whoami-cert # This should match from 003-lets-encrypt.yaml
    kind: ClusterIssuer
  commonName: aks.mydomain.xyz # This is the main DNS name for the cert
  dnsNames:
  - aks.mydomain.xyz # You can add subdomains if you wish